# Generated by Django 4.2.2 on 2023-06-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset',
            field=models.CharField(default='', max_length=36),
        ),
    ]
