# Generated by Django 4.2.2 on 2023-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset',
            new_name='reset_token',
        ),
    ]
