# Generated by Django 4.2.2 on 2023-06-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipping_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.shippinginfo'),
        ),
    ]
