# Generated by Django 4.2.2 on 2023-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='test data', max_length=1800),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='test data', max_length=900),
        ),
        migrations.AddField(
            model_name='order',
            name='optional_address',
            field=models.CharField(blank=True, default='test data', max_length=1800, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='test data', max_length=14),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='test data', max_length=10),
        ),
    ]
