# Generated by Django 4.2.2 on 2023-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_address_order_city_order_optional_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='order',
            name='optional_address',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
