# Generated by Django 4.2.2 on 2023-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Shipped', 'Shipped'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=255),
        ),
    ]
