# Generated by Django 4.2.2 on 2023-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='optional_address',
        ),
    ]
